/*
============================================================================
SQL Topic  : DROP
============================================================================          
*/
-- Question - Drop CollageDB Database

	SHOW DATABASES;
 
	DROP DATABASE CollageDB;
    
-- Question - Drop Table BOOKDETAILS IN Library Database

	USE LibraryDB;
	SHOW TABLES;
    
    DROP TABLE BookDetails;
    SHOW TABLES;
